import streamlit as st
import yfinance as yf
import pandas as pd

# 1. Page Configuration Optimized Explicitly for Mobile Layout Viewports
st.set_page_config(
    page_title="NSE Live 500 Scanner",
    page_icon="⚡",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# Custom Mobile-First CSS Injection 
st.markdown("""
    <style>
    .reportview-container .main .block-container { padding-top: 1rem; padding-bottom: 1rem; }
    h1 { font-size: 24px !important; text-align: center; color: #1E3A8A; margin-bottom: 2px; font-weight: bold; }
    p.sub { text-align: center; font-size: 13px; color: #6B7280; margin-bottom: 15px; }
    div.stButton > button {
        width: 100%;
        background-color: #10B981;
        color: white;
        font-weight: bold;
        padding: 14px;
        border-radius: 8px;
        font-size: 16px;
        border: none;
        box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);
    }
    div.stButton > button:hover { background-color: #059669; color: white; }
    /* Tighten spacing for dense mobile data reading */
    .stDataFrame div { font-size: 14px !important; }
    </style>
""", unsafe_allow_html=True)

st.markdown("<h1>⚡ Nifty 500 Momentum Selector</h1>", unsafe_allow_html=True)
st.markdown("<p class='sub'>Scans 500 liquid scrips for unidirectional momentum shifts</p>", unsafe_allow_html=True)

# 2. Configuration Sliders on Mobile UI 
st.markdown("### 🎛️ Sensitivity Parameters")
vol_threshold = st.slider("Min Volume Surge Multiplier", 1.0, 3.0, 1.5, 0.1)
close_percentile = st.slider("Candle Close Proximity (Top/Bottom %)", 10, 25, 15, 1)

# Convert chosen proximity selection into mathematical percentages
top_cutoff = 1 - (close_percentile / 100)
bottom_cutoff = close_percentile / 100

# 3. Dynamic Basket Loader Engine (Fetches Nifty 500)
@st.cache_data(ttl=86400) # Caches the 500 symbols for 24 hours to keep page reloads instant
def get_nifty_500_tickers():
    try:
        # Pulling live CSV file containing the full list of Nifty 500 stocks
        url = "https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv"
        df = pd.read_csv(url)
        # Append .NS to convert the symbols into valid Yahoo Finance codes
        tickers = [str(symbol).strip() + ".NS" for symbol in df['Symbol'].dropna()]
        return tickers
    except Exception as e:
        # Emergency hardcoded fallback in case the external server undergoes short outages
        return ["RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "SBIN.NS", "ZOMATO.NS", "SUZLON.NS", "JIOFIN.NS"]

# 4. Engine Processing Block
def run_momentum_scan(tickers):
    bullish_list = []
    bearish_list = []
    
    progress_bar = st.progress(0)
    status_text = st.empty()
    total = len(tickers)
    
    for idx, ticker in enumerate(tickers):
        clean_name = ticker.replace(".NS", "")
        status_text.text(f"Scanning {clean_name} ({idx+1}/{total})...")
        progress_bar.progress((idx + 1) / total)
        
        try:
            # Download trailing historical charts (minimum 35 days required to compute trailing averages safely)
            df = yf.download(ticker, period="35d", progress=False, interval="1d")
            if df.empty or len(df) < 21:
                continue
                
            # Structural step to handle multidimensional data arrays if generated by yfinance package updates
            if isinstance(df.columns, pd.MultiIndex):
                df.columns = df.columns.get_level_values(0)
                
            last_row = df.iloc[-1]
            prev_rows = df.iloc[:-1]
            
            close_val = float(last_row['Close'])
            high_val = float(last_row['High'])
            low_val = float(last_row['Low'])
            vol_val = float(last_row['Volume'])
            
            avg_vol_20 = float(prev_rows['Volume'].tail(20).mean())
            candle_range = high_val - low_val
            
            if candle_range == 0 or avg_vol_20 == 0:
                continue
                
            # Mathematical calculation of structural price location and volume metrics
            close_position = (close_val - low_val) / candle_range
            vol_multiplier = vol_val / avg_vol_20
            
            # Check Threshold Filters
            if vol_multiplier >= vol_threshold:
                # Bullish Evaluation Loop
                if close_position >= top_cutoff:
                    bullish_list.append({
                        "Symbol": clean_name,
                        "Close": f"₹{close_val:.2f}",
                        "Vol Multi": f"{vol_multiplier:.2fx}"
                    })
                # Bearish Evaluation Loop
                elif close_position <= bottom_cutoff:
                    bearish_list.append({
                        "Symbol": clean_name,
                        "Close": f"₹{close_val:.2f}",
                        "Vol Multi": f"{vol_multiplier:.2fx}"
                    })
        except:
            continue
            
    progress_bar.empty()
    status_text.empty()
    return pd.DataFrame(bullish_list), pd.DataFrame(bearish_list)

# 5. Interface Trigger Button Functionality
if st.button("🚀 Start Real-Time Nifty 500 Scan"):
    with st.spinner("Fetching live Nifty 500 structural composition..."):
        tickers_list = get_nifty_500_tickers()
        
    st.info(f"Loaded {len(tickers_list)} liquid scrips. Initiating mathematical chart scan...")
    
    bullish_df, bearish_df = run_momentum_scan(tickers_list)
    
    # Render Output Layout Tables on Screen
    st.markdown("### 🔥 Bullish Watchlist")
    if not bullish_df.empty:
        # Sort by highest relative volume multiplier to highlight top institutional activity
        bullish_df = bullish_df.sort_values(by="Vol Multi", ascending=False)
        st.dataframe(bullish_df, use_container_width=True, hide_index=True)
    else:
        st.warning("No scrips qualified. Adjust and lower your threshold filters above.")
        
    st.markdown("### ❄️ Bearish Watchlist")
    if not bearish_df.empty:
        bearish_df = bearish_df.sort_values(by="Vol Multi", ascending=False)
        st.dataframe(bearish_df, use_container_width=True, hide_index=True)
    else:
        st.warning("No scrips qualified. Adjust and lower your threshold filters above.")
        
    st.success("Scan processing complete! Watchlists loaded.")
